services:
  frontend:
    ports:
      - "8443:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
      dockerfile: ./dockerfile
    ports:
      - "2095:2095"
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=production
